---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - make all
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: "i8poLumVpuKDbPgpBmpD38MZ3z4Ri1BfVWqLYOAhWhaZHVFDX4Mazncg8leL0xwVn+aAbX1NozgCVapiPht6I5DRVtEIW/FsgJ9/y9b1mEKoVY3Lvwh2f7Uei5JAWcvt9T8E14gPH48xhPjMCQbNOrWZ/dV/rX0fbUdloyijQhIeNZXCtzo6IZjZLYLaksrw8LkwOnfjYTu+QyqH6Fq/vVbs/AvYh/9ivt9sc8QOva0HdBZIorKW6S7jbPEG2KPdgZNDoPxuul7J9DKk/O6tymBJr+JSL77CVZrxujgsMHqcdANUDJYRjUd6z1iH8MKlyh3ugXXbflv5Nw1DeeZ5QJyJYBGgdz6fQsxDr47oDl09FFNYTmRO6yl9iCLoxXwdedWTPZMbx/+5pI1/ItS7/4mPYMlUjmY1kqfbh8VhMyYDmiWIS1FQjmyDKVxfzfTE3jH0acI2kXLAZ5PuUjuSdddkVVFscWCLMzMkYxx0Tj+GkyYeVcjHEtJX45kaZ856vwRXtJLPu86qPg9TfGzNCCTCm4EHOujYxKgbEeWeM+qNpkv/4yknZ/gwuZYYhqP93coMWfAFlyE3ek4HpM0xNkxV6yaI4AM45tyDmE88pwFjuy+YHFxuhjqJSO5xtsSobssoilcVS3UCnCaPT2dLwD3b4Z7ZOrzIo9xVJXh1Wj0="
    file:
      - cross/ghb0t-linux-amd64.md5
      - cross/ghb0t-windows-386.sha256
      - cross/ghb0t-linux-arm
      - cross/ghb0t-darwin-amd64.md5
      - cross/ghb0t-darwin-amd64
      - cross/ghb0t-solaris-amd64.md5
      - cross/ghb0t-linux-arm64.sha256
      - cross/ghb0t-linux-arm.sha256
      - cross/ghb0t-linux-386.sha256
      - cross/ghb0t-darwin-386.md5
      - cross/ghb0t-windows-386.md5
      - cross/ghb0t-freebsd-amd64.md5
      - cross/ghb0t-linux-arm64.md5
      - cross/ghb0t-linux-arm64
      - cross/ghb0t-freebsd-amd64.sha256
      - cross/ghb0t-freebsd-386.md5
      - cross/ghb0t-linux-amd64.sha256
      - cross/ghb0t-linux-386.md5
      - cross/ghb0t-freebsd-386
      - cross/ghb0t-solaris-amd64.sha256
      - cross/ghb0t-windows-amd64
      - cross/ghb0t-windows-amd64.md5
      - cross/ghb0t-windows-amd64.sha256
      - cross/ghb0t-linux-arm.md5
      - cross/ghb0t-darwin-386.sha256
      - cross/ghb0t-darwin-amd64.sha256
      - cross/ghb0t-windows-386
      - cross/ghb0t-solaris-amd64
      - cross/ghb0t-darwin-386
      - cross/ghb0t-linux-386
      - cross/ghb0t-freebsd-amd64
      - cross/ghb0t-freebsd-386.sha256
      - cross/ghb0t-linux-amd64
    skip_cleanup: true
    on:
      tags: true
